"""
Django settings for Lifeeazy project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_2w#x7sfik6$s5&(d^#fivpf!wg-qf5!-6s07mw+uf8i)(7qez'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# <<<<<<< HEAD:lifeeasy/lifeeasy/settings.py
# ALLOWED_HOSTS = ['7164-123-201-239-238.ngrok.io']
# ALLOWED_HOSTS = ['f977-123-201-239-238.ngrok.io']
# ALLOWED_HOSTS = ['b980-2401-4900-367d-72f4-1caa-4054-77a3-85f5.ngrok.io']
ALLOWED_HOSTS = ['*']
# =======
# ALLOWED_HOSTS = ['6cd8-2409-4070-2381-774e-148d-74b2-e3ff-b9f6.ngrok.io']
# ALLOWED_HOSTS = []

# >>>>>>> 93ad646b3247a4ad30b4142e86a0549619595d3a:Lifeeazy/Lifeeazy/settings.py
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'rest_framework',
    'hcpapi',
    'userappointment',
    'hcpappointment',
    'hcpprescription',
    'profileimage',
    'partners',
    'storages',
    'testapp',



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#

# COGNITO_AWS_REGION = 'ap-south-1' # 'eu-central-1'
# COGNITO_USER_POOL = 'vivifyUserPool'   # 'eu-central-1_xYzaq'
# COGNITO_AUDIENCE = 'ap-south-1_lQYSP2lck'

REST_FRAMEWORK = {
     # 'DEFAULT_PERMISSION_CLASSES':('rest_framework.permissions.AllowAny',),

    # 'DEFAULT_AUTHENTICATION_CLASSES': [
    #     'django_cognito_jwt.JSONWebTokenAuthentication',
        #'rest_framework.authentication.TokenAuthentication',
    #],

}


# SWAGGER_SETTINGS = {
#    'SECURITY_DEFINITIONS': {
#
#       'Bearer': {
#             'type': 'apiKey',
#             'name': 'Authorization',
#             'in': 'header'
#       }
#    }
# }

DATE_INPUT_FORMATS = ('%Y-%m-%d/%H:%M:%S')
# SWAGGER_SETTINGS = {
#     'SECURITY_DEFINITIONS': {
#         'api_Key': {
#                      "type": "http",
#                      "scheme": "bearer",
#                      "bearerFormat": "JWT",
#             # 'type': 'apiKey',
#             # 'in': 'header',
#             # 'name': 'Token Authorization'
#         }
#     },
# }

ROOT_URLCONF = 'Lifeeazy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Lifeeazy.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        # 'NAME': 'admin',
        # 'USERNAME':'dev_user',
        # 'PASSWORD':'dev@1234'

        # Abhishek Commented port setting for database configuration, to be used only if database is on another instance
        # 'CLIENT': {
        # 'host': '3.108.11.120',
        # 'port': 27017
        #        }

        'NAME': 'lifeeazydatabase',
        # 'CLIENT': {
        #     'host': 'localhost',
        #     'port': 27017,
        #     'username': 'dev_user',
        #     'password': 'dev@1234',
        #     'authsource': 'admin',
        #
        # }

    }

}

from .emailsending import *

EMAIL_BACKEND=EMAIL_BACKEND
EMAIL_USE_TLS = EMAIL_USE_TLS
EMAIL_HOST = EMAIL_HOST
FROM_EMAIL=FROM_EMAIL
EMAIL_HOST_USER = EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
EMAIL_PORT = EMAIL_PORT

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/ tmp /'
MEDIA_ROOT = os.path.join(BASE_DIR, 'tmp')

from s3bucket import *

AWS_ACCESS_KEY_ID = AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = AWS_SECRET_ACCESS_KEY
AWS_STORAGE_BUCKET_NAME = AWS_STORAGE_BUCKET_NAME
AWS_S3_SIGNATURE_VERSION = AWS_S3_SIGNATURE_VERSION
AWS_S3_REGION_NAME = AWS_S3_REGION_NAME
AWS_S3_FILE_OVERWRITE = AWS_S3_FILE_OVERWRITE
AWS_DEFAULT_ACL = AWS_DEFAULT_ACL
AWS_S3_VERIFY = AWS_S3_VERIFY
DEFAULT_FILE_STORAGE = DEFAULT_FILE_STORAGE

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
