# Generated by Django 4.0.3 on 2022-04-20 05:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hcpapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Mr', 'Mr')], default='Miss', max_length=10)),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Female', max_length=10)),
                ('ProfilePicture', models.TextField()),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('FamilyMemberType', models.CharField(choices=[('ADULT', 'ADULT'), ('CHILD', 'CHILD')], default='ADULT', max_length=10)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('MartialStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='single', max_length=10)),
                ('BloodGroup', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], default='O+', max_length=10)),
                ('RelationshipToPatient', models.CharField(max_length=10)),
                ('IsEmergency', models.BooleanField()),
            ],
            options={
                'db_table': 'FamilyMember',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='firstname must string and should not be less than 3 and greater than 12', regex='^(?=.{2,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('Lastname', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='lastname must string and should not be less than 3 and greater than 12', regex='^(?=.{2,12}$)(?![_.])(?!.*[_.]{2})[a-zA-Z]+(?<![_.])$')])),
                ('Email', models.EmailField(max_length=50)),
                ('Username', models.CharField(max_length=60, unique=True)),
                ('Password', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='password must contain 8 letters and a captail letter and a special character ', regex='^.*(?=.{8,})(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$')])),
                ('MobileNumber', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('DeviceToken', models.CharField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'User_Data',
            },
        ),
        migrations.CreateModel(
            name='VitalsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('BMI', models.IntegerField()),
                ('Temperature', models.CharField(max_length=255)),
                ('spo2', models.IntegerField()),
                ('BP', models.FloatField()),
                ('Pulse', models.IntegerField()),
                ('FamilyId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitalFamilyid', to='user.familymember')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital', to='user.usermodel')),
            ],
            options={
                'db_table': 'vitalsdata',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(choices=[('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Mr', 'Mr')], default='Miss', max_length=10)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Female', max_length=10)),
                ('ProfilePicture', models.TextField()),
                ('DOB', models.DateField(blank=True, null=True)),
                ('MartialStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='single', max_length=10)),
                ('BloodGroup', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], default='O+', max_length=10)),
                ('UserId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='user.usermodel')),
            ],
            options={
                'db_table': 'User_Profile',
            },
        ),
        migrations.CreateModel(
            name='UserEmergencyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonName', models.CharField(max_length=50)),
                ('RelationshipPatient', models.CharField(max_length=50)),
                ('PrimaryNumber', models.CharField(max_length=50)),
                ('MobileNumber', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('UserId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Emergency', to='user.usermodel')),
            ],
            options={
                'db_table': 'User_EmergencyDetails',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('ZipCode', models.IntegerField()),
                ('PrimaryNumber', models.CharField(max_length=50)),
                ('UserId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='user.usermodel')),
            ],
            options={
                'db_table': 'User_Address',
            },
        ),
        migrations.CreateModel(
            name='LabLevelsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BloodGlucose', models.CharField(max_length=100)),
                ('UrineGloucos', models.CharField(max_length=100)),
                ('HbA1c', models.CharField(max_length=100)),
                ('BloodCholesterol', models.CharField(max_length=100)),
                ('HemoGlobin', models.CharField(max_length=100)),
                ('UrineOutputIn24Hours', models.CharField(max_length=100)),
                ('Others', models.CharField(max_length=100)),
                ('FamilyId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LabLevelFamilyid', to='user.familymember')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LabLevelUserid', to='user.usermodel')),
            ],
            options={
                'db_table': 'LabLevelsTable',
            },
        ),
        migrations.CreateModel(
            name='Individualphysician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FamilyMemberId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Familymemberphysician', to='user.familymember')),
                ('PreferredPhysician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individualphysician', to='hcpapi.hcpmodel')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to='user.usermodel')),
            ],
            options={
                'db_table': 'PreferredPhysicians',
            },
        ),
        migrations.CreateModel(
            name='FamilyMemberAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('ZipCode', models.IntegerField()),
                ('PrimaryNumber', models.CharField(max_length=50)),
                ('FamilyId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FamilyMemberAddress', to='user.familymember')),
            ],
            options={
                'db_table': 'FamilyMemberAddress',
            },
        ),
        migrations.AddField(
            model_name='familymember',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FamilyMemberProfile', to='user.usermodel'),
        ),
        migrations.CreateModel(
            name='EmailVerifyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserId', to='user.usermodel')),
            ],
            options={
                'db_table': 'emailtb',
            },
        ),
        migrations.CreateModel(
            name='AnthropometricsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Female', max_length=10)),
                ('Bmi', models.CharField(max_length=100)),
                ('FamilyId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Anthropometricsfamilyid', to='user.familymember')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Anthropometrics', to='user.usermodel')),
            ],
            options={
                'db_table': 'Bmicalucation',
            },
        ),
        migrations.CreateModel(
            name='Alergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlergiesType', models.CharField(choices=[('Drug', 'Drug'), ('Food', 'Food'), ('Others', 'Others')], default='Drug', max_length=10)),
                ('Reactions', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('Sever', 'Sever')], default='Low', max_length=10)),
                ('Comments', models.CharField(max_length=200)),
                ('FamilyId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AllergiesFamilyid', to='user.familymember')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlergiesUsername', to='user.usermodel')),
            ],
            options={
                'db_table': 'Alergies_Table',
            },
        ),
    ]
