# Generated by Django 4.0.3 on 2022-04-20 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsmodel',
            name='FamilyId',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitalFamilyid', to='user.familymember'),
        ),
    ]
