# Generated by Django 4.0.3 on 2022-04-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HcpScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FromDate', models.DateField()),
                ('ToDate', models.DateField()),
                ('FromTIme', models.TimeField()),
                ('ToTime', models.TimeField()),
                ('TeleconsultationFees', models.IntegerField(blank=True, default=None)),
                ('InclinicFees', models.IntegerField(blank=True, default=None)),
                ('HomeFees', models.IntegerField(blank=True, default=None)),
                ('CurrentDate', models.DateTimeField(auto_now_add=True)),
                ('AppointmentType', models.CharField(max_length=250)),
                ('Fees', models.IntegerField()),
            ],
            options={
                'db_table': 'HCP_Scheduler',
            },
        ),
        migrations.CreateModel(
            name='HcpSelfNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True)),
                ('SelfNote', models.TextField()),
            ],
            options={
                'db_table': 'Hcp_SelfNote',
            },
        ),
    ]
