# Generated by Django 4.0.3 on 2022-04-20 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hcpappointment', '0001_initial'),
        ('hcpapi', '0001_initial'),
        ('userappointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hcpselfnote',
            name='AppointmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AppointmentId', to='userappointment.appointmentmodel'),
        ),
        migrations.AddField(
            model_name='hcpselfnote',
            name='HcpId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfnote', to='hcpapi.hcpmodel'),
        ),
        migrations.AddField(
            model_name='hcpscheduler',
            name='HcpId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule', to='hcpapi.hcpmodel'),
        ),
    ]
