# Generated by Django 4.0.3 on 2022-04-20 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hcpapi', '0001_initial'),
        ('user', '0001_initial'),
        ('hcpappointment', '0001_initial'),
        ('hcpprescription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Specialization', models.CharField(max_length=200)),
                ('Status', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], max_length=10)),
                ('CurrentDate', models.DateTimeField(auto_now_add=True)),
                ('AppointmentType', models.CharField(default=None, max_length=250)),
                ('Fees', models.IntegerField(default=None)),
                ('DoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DoctorSchedule', to='hcpapi.hcpmodel')),
                ('FamilyMemberAge', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Familymemberage', to='user.familymember')),
                ('FamilyMemberGender', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Familymembergender', to='user.familymember')),
                ('FamilyMemberId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FamilyAppointment', to='user.familymember')),
                ('PrescriptionId', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prescription', to='hcpprescription.userprescription')),
                ('ScheduleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Scheduleid', to='hcpappointment.hcpscheduler')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='user.usermodel')),
            ],
            options={
                'db_table': 'User_Appointment',
            },
        ),
        migrations.CreateModel(
            name='VideoConsultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateField()),
                ('Status', models.CharField(choices=[('InCompleted', 'InCompleted'), ('Half', 'Half'), ('Completed', 'Completed')], default='InCompleted', max_length=100)),
                ('Duration', models.CharField(max_length=100)),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideoConsultModel', to='userappointment.appointmentmodel')),
            ],
            options={
                'db_table': 'VideoConsult_table',
            },
        ),
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionId', models.CharField(max_length=1000)),
                ('Date', models.DateField()),
                ('Amount', models.IntegerField()),
                ('AppointmentType', models.CharField(max_length=250)),
                ('DoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorbilling', to='hcpapi.hcpmodel')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='user.usermodel')),
            ],
            options={
                'db_table': 'BillingTable',
            },
        ),
    ]
